# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c567bef1b32cbc2d3922078ff71987cca9547dce681f69ed69f9b6c9a1194465906f3187676d400977ca1c4b61ed2617191aa8f178f813aeb570cf8a8765a3ce

test:
  secret_key_base: 2d55b6ac1b9ec6882ab4e773d7f0b8da838601d58244117674e23823ca9fc08cdeaf83e3cfea67390a501892871d6ab221e909a69ab6c82fcdb8e57ac32c7def

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
