# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Association.destroy_all
Item.destroy_all

new_item = Item.create(name: 'Artichoke')
Association.create!([{name: 'Asparagus', ranking: 50, item: new_item}, {name: 'Broccoli', ranking: 50, item: new_item}, {name: 'Collard greens', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Arugula')
Association.create!([{name: 'Carrots', ranking: 50, item: new_item}, {name: 'Onions', ranking: 50, item: new_item}, {name: 'Celery', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Asparagus')
Association.create!([{name: 'Carrots', ranking: 50, item: new_item}, {name: 'Cabbage', ranking: 50, item: new_item}, {name: 'Tomatoes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Avocado')
Association.create!([{name: 'Peppers', ranking: 50, item: new_item}, {name: 'Kohlrabi', ranking: 50, item: new_item}, {name: 'Chard', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Bamboo shoots')
Association.create!([{name: 'Corn', ranking: 50, item: new_item}, {name: 'Crisphead lettuce', ranking: 50, item: new_item}, {name: 'Sprouts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Beets')
Association.create!([{name: 'Watercress', ranking: 50, item: new_item}, {name: 'Garlic', ranking: 50, item: new_item}, {name: 'Tomatillo', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Bell peppers')
Association.create!([{name: 'Cucumber', ranking: 50, item: new_item}, {name: 'Brussels sprouts', ranking: 50, item: new_item}, {name: 'Tomatoes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Bok choy')
Association.create!([{name: 'Sprouts', ranking: 50, item: new_item}, {name: 'Endive', ranking: 50, item: new_item}, {name: 'Tomatoes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Broccoli')
Association.create!([{name: 'Nopales', ranking: 50, item: new_item}, {name: 'Water chestnuts', ranking: 50, item: new_item}, {name: 'Asparagus', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Brussels sprouts')
Association.create!([{name: 'Potatoes', ranking: 50, item: new_item}, {name: 'Daikon', ranking: 50, item: new_item}, {name: 'Bell peppers', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cabbage')
Association.create!([{name: 'Onions', ranking: 50, item: new_item}, {name: 'Carrots', ranking: 50, item: new_item}, {name: 'Collard greens', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Carrots')
Association.create!([{name: 'Eggplant', ranking: 50, item: new_item}, {name: 'Artichoke', ranking: 50, item: new_item}, {name: 'Endive', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cassava')
Association.create!([{name: 'Corn', ranking: 50, item: new_item}, {name: 'Turnips', ranking: 50, item: new_item}, {name: 'Tomatillo', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cauliflower')
Association.create!([{name: 'Cucumber', ranking: 50, item: new_item}, {name: 'Brussels sprouts', ranking: 50, item: new_item}, {name: 'Water chestnuts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Celery')
Association.create!([{name: 'Shallots', ranking: 50, item: new_item}, {name: 'Zucchini', ranking: 50, item: new_item}, {name: 'Sweet potatoes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Chard')
Association.create!([{name: 'Jicama', ranking: 50, item: new_item}, {name: 'Radicchio', ranking: 50, item: new_item}, {name: 'Sprouts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Collard greens')
Association.create!([{name: 'Kale', ranking: 50, item: new_item}, {name: 'Endive', ranking: 50, item: new_item}, {name: 'Romaine lettuce', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Corn')
Association.create!([{name: 'Asparagus', ranking: 50, item: new_item}, {name: 'Tomatillo', ranking: 50, item: new_item}, {name: 'Cucumber', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Crisphead lettuce')
Association.create!([{name: 'Okra', ranking: 50, item: new_item}, {name: 'Asparagus', ranking: 50, item: new_item}, {name: 'Peas', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cucumber')
Association.create!([{name: 'Spinach', ranking: 50, item: new_item}, {name: 'Ginger', ranking: 50, item: new_item}, {name: 'Water chestnuts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Daikon')
Association.create!([{name: 'Water chestnuts', ranking: 50, item: new_item}, {name: 'Tomatillo', ranking: 50, item: new_item}, {name: 'Eggplant', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Eggplant')
Association.create!([{name: 'Tomatoes', ranking: 50, item: new_item}, {name: 'Sprouts', ranking: 50, item: new_item}, {name: 'Avocado', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Endive')
Association.create!([{name: 'Tomatoes', ranking: 50, item: new_item}, {name: 'Peppers', ranking: 50, item: new_item}, {name: 'Radishes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Garlic')
Association.create!([{name: 'Kale', ranking: 50, item: new_item}, {name: 'Onions', ranking: 50, item: new_item}, {name: 'Brussels sprouts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Ginger')
Association.create!([{name: 'Avocado', ranking: 50, item: new_item}, {name: 'Radicchio', ranking: 50, item: new_item}, {name: 'Zucchini', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Hot peppers')
Association.create!([{name: 'Turnips', ranking: 50, item: new_item}, {name: 'Corn', ranking: 50, item: new_item}, {name: 'Broccoli', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Jicama')
Association.create!([{name: 'Cauliflower', ranking: 50, item: new_item}, {name: 'Watercress', ranking: 50, item: new_item}, {name: 'Cucumber', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Kale')
Association.create!([{name: 'Watercress', ranking: 50, item: new_item}, {name: 'Chard', ranking: 50, item: new_item}, {name: 'Peas', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Kohlrabi')
Association.create!([{name: 'Collard greens', ranking: 50, item: new_item}, {name: 'Cassava', ranking: 50, item: new_item}, {name: 'Broccoli', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Leaf lettuce')
Association.create!([{name: 'Bamboo shoots', ranking: 50, item: new_item}, {name: 'Arugula', ranking: 50, item: new_item}, {name: 'Crisphead lettuce', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Mushrooms')
Association.create!([{name: 'Asparagus', ranking: 50, item: new_item}, {name: 'Bok choy', ranking: 50, item: new_item}, {name: 'Potatoes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Nopales')
Association.create!([{name: 'Eggplant', ranking: 50, item: new_item}, {name: 'Watercress', ranking: 50, item: new_item}, {name: 'Sweet potatoes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Okra')
Association.create!([{name: 'Kale', ranking: 50, item: new_item}, {name: 'Mushrooms', ranking: 50, item: new_item}, {name: 'Garlic', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Onions')
Association.create!([{name: 'Bell peppers', ranking: 50, item: new_item}, {name: 'Taro', ranking: 50, item: new_item}, {name: 'Ginger', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Peas')
Association.create!([{name: 'Corn', ranking: 50, item: new_item}, {name: 'Avocado', ranking: 50, item: new_item}, {name: 'Okra', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Potatoes')
Association.create!([{name: 'Zucchini', ranking: 50, item: new_item}, {name: 'Cucumber', ranking: 50, item: new_item}, {name: 'Cassava', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Radishes')
Association.create!([{name: 'Squash', ranking: 50, item: new_item}, {name: 'Radicchio', ranking: 50, item: new_item}, {name: 'Zucchini', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Radicchio')
Association.create!([{name: 'Hot peppers', ranking: 50, item: new_item}, {name: 'Cucumber', ranking: 50, item: new_item}, {name: 'Endive', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Romaine lettuce')
Association.create!([{name: 'Arugula', ranking: 50, item: new_item}, {name: 'Corn', ranking: 50, item: new_item}, {name: 'Tomatillo', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Shallots')
Association.create!([{name: 'Zucchini', ranking: 50, item: new_item}, {name: 'Carrots', ranking: 50, item: new_item}, {name: 'Broccoli', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Leeks')
Association.create!([{name: 'Shallots', ranking: 50, item: new_item}, {name: 'Water chestnuts', ranking: 50, item: new_item}, {name: 'Corn', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Spinach')
Association.create!([{name: 'Artichoke', ranking: 50, item: new_item}, {name: 'Bamboo shoots', ranking: 50, item: new_item}, {name: 'Asparagus', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sprouts')
Association.create!([{name: 'Garlic', ranking: 50, item: new_item}, {name: 'Water chestnuts', ranking: 50, item: new_item}, {name: 'Corn', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Squash')
Association.create!([{name: 'Cauliflower', ranking: 50, item: new_item}, {name: 'Ginger', ranking: 50, item: new_item}, {name: 'Tomatillo', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sweet potatoes')
Association.create!([{name: 'Corn', ranking: 50, item: new_item}, {name: 'Beets', ranking: 50, item: new_item}, {name: 'Radicchio', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Taro')
Association.create!([{name: 'Sprouts', ranking: 50, item: new_item}, {name: 'Potatoes', ranking: 50, item: new_item}, {name: 'Leaf lettuce', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Tomatillo')
Association.create!([{name: 'Daikon', ranking: 50, item: new_item}, {name: 'Turnips', ranking: 50, item: new_item}, {name: 'Radishes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Tomatoes')
Association.create!([{name: 'Cucumber', ranking: 50, item: new_item}, {name: 'Crisphead lettuce', ranking: 50, item: new_item}, {name: 'Eggplant', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Turnips')
Association.create!([{name: 'Parsnips', ranking: 50, item: new_item}, {name: 'Leeks', ranking: 50, item: new_item}, {name: 'Carrots', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Parsnips')
Association.create!([{name: 'Water chestnuts', ranking: 50, item: new_item}, {name: 'Carrots', ranking: 50, item: new_item}, {name: 'Zucchini', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Water chestnuts')
Association.create!([{name: 'Kohlrabi', ranking: 50, item: new_item}, {name: 'Soy Sauce', ranking: 50, item: new_item}, {name: 'Bell peppers', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Watercress')
Association.create!([{name: 'Zucchini', ranking: 50, item: new_item}, {name: 'Tomatillo', ranking: 50, item: new_item}, {name: 'Mushrooms', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Zucchini')
Association.create!([{name: 'Beets', ranking: 50, item: new_item}, {name: 'Okra', ranking: 50, item: new_item}, {name: 'Squash', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pimientos')
Association.create!([{name: 'Peppers', ranking: 50, item: new_item}, {name: 'Pickles', ranking: 50, item: new_item}, {name: 'Olives', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Almonds')
Association.create!([{name: 'Brazil nuts', ranking: 50, item: new_item}, {name: 'Macadamia', ranking: 50, item: new_item}, {name: 'Peanuts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Brazil nuts')
Association.create!([{name: 'Peanuts', ranking: 50, item: new_item}, {name: 'Pecans', ranking: 50, item: new_item}, {name: 'Pine nuts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cashews')
Association.create!([{name: 'Walnuts', ranking: 50, item: new_item}, {name: 'Pine nuts', ranking: 50, item: new_item}, {name: 'Chocolate Chips', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Chestnuts')
Association.create!([{name: 'Almonds', ranking: 50, item: new_item}, {name: 'Pistachios', ranking: 50, item: new_item}, {name: 'Peanuts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Macadamia')
Association.create!([{name: 'Pine nuts', ranking: 50, item: new_item}, {name: 'Chestnuts', ranking: 50, item: new_item}, {name: 'Peanuts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Peanuts')
Association.create!([{name: 'Pistachios', ranking: 50, item: new_item}, {name: 'Cashews', ranking: 50, item: new_item}, {name: 'Macadamia', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pecans')
Association.create!([{name: 'Pine nuts', ranking: 50, item: new_item}, {name: 'Pistachios', ranking: 50, item: new_item}, {name: 'Peanuts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pine nuts')
Association.create!([{name: 'Pistachios', ranking: 50, item: new_item}, {name: 'Pasta', ranking: 50, item: new_item}, {name: 'Pecans', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pistachios')
Association.create!([{name: 'Cashews', ranking: 50, item: new_item}, {name: 'Apples', ranking: 50, item: new_item}, {name: 'Almonds', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Walnuts')
Association.create!([{name: 'Chestnuts', ranking: 50, item: new_item}, {name: 'Pistachios', ranking: 50, item: new_item}, {name: 'Peanuts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Potato sticks')
Association.create!([{name: 'Potato chips', ranking: 50, item: new_item}, {name: 'Popcorn', ranking: 50, item: new_item}, {name: 'Peanuts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Flax Seeds')
Association.create!([{name: 'Lotus Seeds', ranking: 50, item: new_item}, {name: 'Sunflower Seeds', ranking: 50, item: new_item}, {name: 'Walnuts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Lotus Seeds')
Association.create!([{name: 'Flax Seeds', ranking: 50, item: new_item}, {name: 'Sunflower Seeds', ranking: 50, item: new_item}, {name: 'Walnuts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pumpkin Seeds')
Association.create!([{name: 'Sunflower Seeds', ranking: 50, item: new_item}, {name: 'Lotus Seeds', ranking: 50, item: new_item}, {name: 'Walnuts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sunflower Seeds')
Association.create!([{name: 'Pumpkin Seeds', ranking: 50, item: new_item}, {name: 'Walnuts', ranking: 50, item: new_item}, {name: 'Lotus Seeds', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Apples')
Association.create!([{name: 'Grapefruit', ranking: 50, item: new_item}, {name: 'Pears', ranking: 50, item: new_item}, {name: 'Blueberries', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Apricots')
Association.create!([{name: 'Nectarines', ranking: 50, item: new_item}, {name: 'Guava', ranking: 50, item: new_item}, {name: 'Limes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Avocados')
Association.create!([{name: 'Muskmelon', ranking: 50, item: new_item}, {name: 'Lemons', ranking: 50, item: new_item}, {name: 'Raspberries', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Bananas')
Association.create!([{name: 'Muskmelon', ranking: 50, item: new_item}, {name: 'Apples', ranking: 50, item: new_item}, {name: 'Grapes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Blackberries')
Association.create!([{name: 'Plums', ranking: 50, item: new_item}, {name: 'Muskmelon', ranking: 50, item: new_item}, {name: 'Strawberries', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Blueberries')
Association.create!([{name: 'Apples', ranking: 50, item: new_item}, {name: 'Kiwis', ranking: 50, item: new_item}, {name: 'Grapes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cantaloupe')
Association.create!([{name: 'Plantains', ranking: 50, item: new_item}, {name: 'Watermelon', ranking: 50, item: new_item}, {name: 'Muskmelon', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cherries')
Association.create!([{name: 'Cantaloupe', ranking: 50, item: new_item}, {name: 'Grapes', ranking: 50, item: new_item}, {name: 'Olives', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cranberries')
Association.create!([{name: 'Grapes', ranking: 50, item: new_item}, {name: 'Rhubarb', ranking: 50, item: new_item}, {name: 'Blackberries', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Dates')
Association.create!([{name: 'Strawberries', ranking: 50, item: new_item}, {name: 'Apricots', ranking: 50, item: new_item}, {name: 'Blueberries', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Figs')
Association.create!([{name: 'Dates', ranking: 50, item: new_item}, {name: 'Kiwis', ranking: 50, item: new_item}, {name: 'Blueberries', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Grapes')
Association.create!([{name: 'Lemons', ranking: 50, item: new_item}, {name: 'Bananas', ranking: 50, item: new_item}, {name: 'Cherries', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Grapefruit')
Association.create!([{name: 'Cranberries', ranking: 50, item: new_item}, {name: 'Pineapple', ranking: 50, item: new_item}, {name: 'Kumquats', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Guava')
Association.create!([{name: 'Cranberries', ranking: 50, item: new_item}, {name: 'Strawberries', ranking: 50, item: new_item}, {name: 'Apricots', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Muskmelon')
Association.create!([{name: 'Kiwis', ranking: 50, item: new_item}, {name: 'Apples', ranking: 50, item: new_item}, {name: 'Limes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Honeydew melon')
Association.create!([{name: 'Watermelon', ranking: 50, item: new_item}, {name: 'Cranberries', ranking: 50, item: new_item}, {name: 'Blueberries', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Kiwis')
Association.create!([{name: 'Apricots', ranking: 50, item: new_item}, {name: 'Raspberries', ranking: 50, item: new_item}, {name: 'Oranges', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Kumquats')
Association.create!([{name: 'Pears', ranking: 50, item: new_item}, {name: 'Honeydew melon', ranking: 50, item: new_item}, {name: 'Rhubarb', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Lemons')
Association.create!([{name: 'Limes', ranking: 50, item: new_item}, {name: 'Kumquats', ranking: 50, item: new_item}, {name: 'Rhubarb', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Limes')
Association.create!([{name: 'Kiwis', ranking: 50, item: new_item}, {name: 'Bananas', ranking: 50, item: new_item}, {name: 'Pomegranate', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Lychee')
Association.create!([{name: 'Grapes', ranking: 50, item: new_item}, {name: 'Soy Sauce', ranking: 50, item: new_item}, {name: 'Pineapple', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Mango')
Association.create!([{name: 'Pears', ranking: 50, item: new_item}, {name: 'Honeydew melon', ranking: 50, item: new_item}, {name: 'Plantains', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Mangosteen')
Association.create!([{name: 'Watermelon', ranking: 50, item: new_item}, {name: 'Peaches', ranking: 50, item: new_item}, {name: 'Honeydew melon', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Nectarines')
Association.create!([{name: 'Papaya', ranking: 50, item: new_item}, {name: 'Apples', ranking: 50, item: new_item}, {name: 'Quince', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Oranges')
Association.create!([{name: 'Nectarines', ranking: 50, item: new_item}, {name: 'Apricots', ranking: 50, item: new_item}, {name: 'Avocados', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Papaya')
Association.create!([{name: 'Mango', ranking: 50, item: new_item}, {name: 'Strawberries', ranking: 50, item: new_item}, {name: 'Quince', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Peaches')
Association.create!([{name: 'Nectarines', ranking: 50, item: new_item}, {name: 'Strawberries', ranking: 50, item: new_item}, {name: 'Pears', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pears')
Association.create!([{name: 'Peaches', ranking: 50, item: new_item}, {name: 'Apples', ranking: 50, item: new_item}, {name: 'Strawberries', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pineapple')
Association.create!([{name: 'Nectarines', ranking: 50, item: new_item}, {name: 'Pears', ranking: 50, item: new_item}, {name: 'Mango', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Plantains')
Association.create!([{name: 'Guava', ranking: 50, item: new_item}, {name: 'Strawberries', ranking: 50, item: new_item}, {name: 'Cranberries', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Plums')
Association.create!([{name: 'Dates', ranking: 50, item: new_item}, {name: 'Muskmelon', ranking: 50, item: new_item}, {name: 'Kiwis', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pomegranate')
Association.create!([{name: 'Blueberries', ranking: 50, item: new_item}, {name: 'Dates', ranking: 50, item: new_item}, {name: 'Bananas', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Quince')
Association.create!([{name: 'Watermelon', ranking: 50, item: new_item}, {name: 'Blackberries', ranking: 50, item: new_item}, {name: 'Papaya', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Raspberries')
Association.create!([{name: 'Peaches', ranking: 50, item: new_item}, {name: 'Figs', ranking: 50, item: new_item}, {name: 'Blueberries', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Rhubarb')
Association.create!([{name: 'Lychee', ranking: 50, item: new_item}, {name: 'Blueberries', ranking: 50, item: new_item}, {name: 'Limes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Strawberries')
Association.create!([{name: 'Grapefruit', ranking: 50, item: new_item}, {name: 'Grapes', ranking: 50, item: new_item}, {name: 'Blueberries', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Watermelon')
Association.create!([{name: 'Pineapple', ranking: 50, item: new_item}, {name: 'Avocados', ranking: 50, item: new_item}, {name: 'Nectarines', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Beans')
Association.create!([{name: 'Pinto beans', ranking: 50, item: new_item}, {name: 'Lentils', ranking: 50, item: new_item}, {name: 'Split peas', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Black beans')
Association.create!([{name: 'Fava beans', ranking: 50, item: new_item}, {name: 'Beans', ranking: 50, item: new_item}, {name: 'Black-eyed peas', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Black-eyed peas')
Association.create!([{name: 'Pinto beans', ranking: 50, item: new_item}, {name: 'Kidney beans', ranking: 50, item: new_item}, {name: 'White beans', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Chickpeas')
Association.create!([{name: 'Lima beans', ranking: 50, item: new_item}, {name: 'Red beans', ranking: 50, item: new_item}, {name: 'Mung beans', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Edamame')
Association.create!([{name: 'Split peas', ranking: 50, item: new_item}, {name: 'Mung beans', ranking: 50, item: new_item}, {name: 'Mushrooms', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Fava beans')
Association.create!([{name: 'Split peas', ranking: 50, item: new_item}, {name: 'Lentils', ranking: 50, item: new_item}, {name: 'Chickpeas', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Kidney beans')
Association.create!([{name: 'Beans', ranking: 50, item: new_item}, {name: 'White beans', ranking: 50, item: new_item}, {name: 'Split peas', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Lentils')
Association.create!([{name: 'Pasta', ranking: 50, item: new_item}, {name: 'Black-eyed peas', ranking: 50, item: new_item}, {name: 'Black beans', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Lima beans')
Association.create!([{name: 'White beans', ranking: 50, item: new_item}, {name: 'Mung beans', ranking: 50, item: new_item}, {name: 'Red beans', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Mung beans')
Association.create!([{name: 'Red beans', ranking: 50, item: new_item}, {name: 'White beans', ranking: 50, item: new_item}, {name: 'Spinach', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Navy beans')
Association.create!([{name: 'Beans', ranking: 50, item: new_item}, {name: 'Black-eyed peas', ranking: 50, item: new_item}, {name: 'Split peas', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pinto beans')
Association.create!([{name: 'Lentils', ranking: 50, item: new_item}, {name: 'White beans', ranking: 50, item: new_item}, {name: 'Navy beans', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Red beans')
Association.create!([{name: 'Lima beans', ranking: 50, item: new_item}, {name: 'White beans', ranking: 50, item: new_item}, {name: 'Kidney beans', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Split peas')
Association.create!([{name: 'Navy beans', ranking: 50, item: new_item}, {name: 'Black-eyed peas', ranking: 50, item: new_item}, {name: 'Carrots', ranking: 50, item: new_item}])
new_item = Item.create(name: 'White beans')
Association.create!([{name: 'Chickpeas', ranking: 50, item: new_item}, {name: 'Split peas', ranking: 50, item: new_item}, {name: 'Black beans', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Amaranth')
Association.create!([{name: 'Rice', ranking: 50, item: new_item}, {name: 'Sorghum', ranking: 50, item: new_item}, {name: 'Soy sauce', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Barley')
Association.create!([{name: 'Bulgar', ranking: 50, item: new_item}, {name: 'Amaranth', ranking: 50, item: new_item}, {name: 'White rice', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Brown rice')
Association.create!([{name: 'Cornmeal', ranking: 50, item: new_item}, {name: 'Sorghum', ranking: 50, item: new_item}, {name: 'Beans', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Buckwheat')
Association.create!([{name: 'Flour', ranking: 50, item: new_item}, {name: 'Quinoa', ranking: 50, item: new_item}, {name: 'Bulgar', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Bulgar')
Association.create!([{name: 'Cornmeal', ranking: 50, item: new_item}, {name: 'Sorghum', ranking: 50, item: new_item}, {name: 'White rice', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cornmeal')
Association.create!([{name: 'Amaranth', ranking: 50, item: new_item}, {name: 'Bulgar', ranking: 50, item: new_item}, {name: 'Barley', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Couscous')
Association.create!([{name: 'Millet', ranking: 50, item: new_item}, {name: 'Barley', ranking: 50, item: new_item}, {name: 'White rice', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Millet')
Association.create!([{name: 'Wild rice', ranking: 50, item: new_item}, {name: 'Oatmeal', ranking: 50, item: new_item}, {name: 'Seeds', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Oatmeal')
Association.create!([{name: 'Bulgar', ranking: 50, item: new_item}, {name: 'Couscous', ranking: 50, item: new_item}, {name: 'Cornmeal', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sorghum')
Association.create!([{name: 'Amaranth', ranking: 50, item: new_item}, {name: 'Wild rice', ranking: 50, item: new_item}, {name: 'Cornmeal', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Wheat gluten (Seitan)')
Association.create!([{name: 'Flour', ranking: 50, item: new_item}, {name: 'Bulgar', ranking: 50, item: new_item}, {name: 'Buckwheat', ranking: 50, item: new_item}])
new_item = Item.create(name: 'White rice')
Association.create!([{name: 'Wild rice', ranking: 50, item: new_item}, {name: 'Sorghum', ranking: 50, item: new_item}, {name: 'Beans', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Wild rice')
Association.create!([{name: 'Oatmeal', ranking: 50, item: new_item}, {name: 'White rice', ranking: 50, item: new_item}, {name: 'Beans', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Mint')
Association.create!([{name: 'Thyme', ranking: 50, item: new_item}, {name: 'Allspice', ranking: 50, item: new_item}, {name: 'Chives', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Allspice')
Association.create!([{name: 'Paprika', ranking: 50, item: new_item}, {name: 'Garlic', ranking: 50, item: new_item}, {name: 'Cilantro', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Anise')
Association.create!([{name: 'Thyme', ranking: 50, item: new_item}, {name: 'Tarragon', ranking: 50, item: new_item}, {name: 'Nutmeg', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Bay leaf')
Association.create!([{name: 'Nutmeg', ranking: 50, item: new_item}, {name: 'Cilantro', ranking: 50, item: new_item}, {name: 'Sage', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Basil')
Association.create!([{name: 'Red pepper', ranking: 50, item: new_item}, {name: 'Clove', ranking: 50, item: new_item}, {name: 'Cinnamon', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Black pepper')
Association.create!([{name: 'Nutmeg', ranking: 50, item: new_item}, {name: 'Cilantro', ranking: 50, item: new_item}, {name: 'Bay leaf', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cayenne pepper')
Association.create!([{name: 'Sage', ranking: 50, item: new_item}, {name: 'Anise', ranking: 50, item: new_item}, {name: 'Poppy seed', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Celery seed')
Association.create!([{name: 'Black pepper', ranking: 50, item: new_item}, {name: 'Cinnamon', ranking: 50, item: new_item}, {name: 'Paprika', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Chives')
Association.create!([{name: 'Chili powder', ranking: 50, item: new_item}, {name: 'Mint', ranking: 50, item: new_item}, {name: 'Scallions', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Chili powder')
Association.create!([{name: 'Cilantro', ranking: 50, item: new_item}, {name: 'Rosemary', ranking: 50, item: new_item}, {name: 'Peppermint', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cilantro')
Association.create!([{name: 'Coriander', ranking: 50, item: new_item}, {name: 'Clove', ranking: 50, item: new_item}, {name: 'Allspice', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cinnamon')
Association.create!([{name: 'Rosemary', ranking: 50, item: new_item}, {name: 'Lavender', ranking: 50, item: new_item}, {name: 'Sage', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Clove')
Association.create!([{name: 'Cayenne pepper', ranking: 50, item: new_item}, {name: 'Mint', ranking: 50, item: new_item}, {name: 'Spearmint', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Coriander')
Association.create!([{name: 'Vanilla extract', ranking: 50, item: new_item}, {name: 'Black pepper', ranking: 50, item: new_item}, {name: 'Peppermint', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cumin')
Association.create!([{name: 'Oregano', ranking: 50, item: new_item}, {name: 'Garlic', ranking: 50, item: new_item}, {name: 'Celery seed', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Dill')
Association.create!([{name: 'Red pepper', ranking: 50, item: new_item}, {name: 'Bay leaf', ranking: 50, item: new_item}, {name: 'Turmeric', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Fennel')
Association.create!([{name: 'Marjoram', ranking: 50, item: new_item}, {name: 'Spearmint', ranking: 50, item: new_item}, {name: 'Turmeric', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Garlic')
Association.create!([{name: 'Thyme', ranking: 50, item: new_item}, {name: 'Parsley', ranking: 50, item: new_item}, {name: 'Chives', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Lavender')
Association.create!([{name: 'Peppermint', ranking: 50, item: new_item}, {name: 'Anise', ranking: 50, item: new_item}, {name: 'Cumin', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Lemongrass')
Association.create!([{name: 'Cumin', ranking: 50, item: new_item}, {name: 'Poppy seed', ranking: 50, item: new_item}, {name: 'Spearmint', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Marjoram')
Association.create!([{name: 'Lavender', ranking: 50, item: new_item}, {name: 'Nutmeg', ranking: 50, item: new_item}, {name: 'Lemongrass', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Nutmeg')
Association.create!([{name: 'Chili powder', ranking: 50, item: new_item}, {name: 'Oregano', ranking: 50, item: new_item}, {name: 'Coriander', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Oregano')
Association.create!([{name: 'Sage', ranking: 50, item: new_item}, {name: 'Poppy seed', ranking: 50, item: new_item}, {name: 'Rosemary', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Paprika')
Association.create!([{name: 'Oregano', ranking: 50, item: new_item}, {name: 'Allspice', ranking: 50, item: new_item}, {name: 'Fennel', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Parsley')
Association.create!([{name: 'Red pepper', ranking: 50, item: new_item}, {name: 'Salt', ranking: 50, item: new_item}, {name: 'Rosemary', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Peppermint')
Association.create!([{name: 'Celery seed', ranking: 50, item: new_item}, {name: 'Clove', ranking: 50, item: new_item}, {name: 'Coriander', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Poppy seed')
Association.create!([{name: 'Thyme', ranking: 50, item: new_item}, {name: 'Salt', ranking: 50, item: new_item}, {name: 'Cayenne pepper', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Red pepper')
Association.create!([{name: 'Bay leaf', ranking: 50, item: new_item}, {name: 'Cinnamon', ranking: 50, item: new_item}, {name: 'Rosemary', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Rosemary')
Association.create!([{name: 'Black pepper', ranking: 50, item: new_item}, {name: 'Lavender', ranking: 50, item: new_item}, {name: 'Allspice', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Saffron')
Association.create!([{name: 'Red pepper', ranking: 50, item: new_item}, {name: 'Turmeric', ranking: 50, item: new_item}, {name: 'Tarragon', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sage')
Association.create!([{name: 'Black pepper', ranking: 50, item: new_item}, {name: 'Cinnamon', ranking: 50, item: new_item}, {name: 'Dill', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Spearmint')
Association.create!([{name: 'Chili powder', ranking: 50, item: new_item}, {name: 'Clove', ranking: 50, item: new_item}, {name: 'Rosemary', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Tarragon')
Association.create!([{name: 'Black pepper', ranking: 50, item: new_item}, {name: 'Garlic', ranking: 50, item: new_item}, {name: 'Cinnamon', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Salt')
Association.create!([{name: 'Fennel', ranking: 50, item: new_item}, {name: 'Red pepper', ranking: 50, item: new_item}, {name: 'Flour', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Thyme')
Association.create!([{name: 'Turmeric', ranking: 50, item: new_item}, {name: 'Anise', ranking: 50, item: new_item}, {name: 'Mint', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Turmeric')
Association.create!([{name: 'Chives', ranking: 50, item: new_item}, {name: 'Oregano', ranking: 50, item: new_item}, {name: 'Red pepper', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Vanilla extract')
Association.create!([{name: 'Nutmeg', ranking: 50, item: new_item}, {name: 'Mint', ranking: 50, item: new_item}, {name: 'Clove', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Applesauce')
Association.create!([{name: 'Baked beans', ranking: 50, item: new_item}, {name: 'Pickles', ranking: 50, item: new_item}, {name: 'Canned Corn', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Baked beans')
Association.create!([{name: 'Olives', ranking: 50, item: new_item}, {name: 'Canned Corn', ranking: 50, item: new_item}, {name: 'Chili', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Chili')
Association.create!([{name: 'Beans', ranking: 50, item: new_item}, {name: 'Applesauce', ranking: 50, item: new_item}, {name: 'Soups', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Olives')
Association.create!([{name: 'Soups', ranking: 50, item: new_item}, {name: 'Tomato sauce', ranking: 50, item: new_item}, {name: 'Chili', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Soups')
Association.create!([{name: 'Sauces', ranking: 50, item: new_item}, {name: 'Olive oil', ranking: 50, item: new_item}, {name: 'Olives', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Vegetable broth')
Association.create!([{name: 'Soups', ranking: 50, item: new_item}, {name: 'Tomato sauce', ranking: 50, item: new_item}, {name: 'Baked beans', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Agave nectar')
Association.create!([{name: 'Sugar', ranking: 50, item: new_item}, {name: 'Gravy', ranking: 50, item: new_item}, {name: 'Honey', ranking: 50, item: new_item}])
new_item = Item.create(name: 'BBQ sauce')
Association.create!([{name: 'Mustard', ranking: 50, item: new_item}, {name: 'Hot sauce', ranking: 50, item: new_item}, {name: 'Sriracha', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Brown rice syrup')
Association.create!([{name: 'Mustard', ranking: 50, item: new_item}, {name: 'Mayonnaise', ranking: 50, item: new_item}, {name: 'Salad dressing', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Gravy')
Association.create!([{name: 'Salad dressing', ranking: 50, item: new_item}, {name: 'Brown rice syrup', ranking: 50, item: new_item}, {name: 'Mayonnaise', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Harissa')
Association.create!([{name: 'Steak sauce', ranking: 50, item: new_item}, {name: 'Stir fry sauce', ranking: 50, item: new_item}, {name: 'Hot sauce', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Honey')
Association.create!([{name: 'Steak sauce', ranking: 50, item: new_item}, {name: 'Ponzu', ranking: 50, item: new_item}, {name: 'Salad dressing', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Hot sauce')
Association.create!([{name: 'Honey', ranking: 50, item: new_item}, {name: 'BBQ sauce', ranking: 50, item: new_item}, {name: 'Mustard', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Jam')
Association.create!([{name: 'Stir fry sauce', ranking: 50, item: new_item}, {name: 'Jelly', ranking: 50, item: new_item}, {name: 'Relish', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Jelly')
Association.create!([{name: 'Brown rice syrup', ranking: 50, item: new_item}, {name: 'Harissa', ranking: 50, item: new_item}, {name: 'Tomato sauce', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Chutney')
Association.create!([{name: 'Ketchup', ranking: 50, item: new_item}, {name: 'Mustard', ranking: 50, item: new_item}, {name: 'BBQ sauce', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Ketchup')
Association.create!([{name: 'Worcestershire', ranking: 50, item: new_item}, {name: 'Mustard', ranking: 50, item: new_item}, {name: 'Steak sauce', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Mustard')
Association.create!([{name: 'Hot sauce', ranking: 50, item: new_item}, {name: 'Agave nectar', ranking: 50, item: new_item}, {name: 'BBQ sauce', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Maple syrup')
Association.create!([{name: 'Jam', ranking: 50, item: new_item}, {name: 'Harissa', ranking: 50, item: new_item}, {name: 'Pancake mix', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Mayonnaise')
Association.create!([{name: 'Mustard', ranking: 50, item: new_item}, {name: 'Peanut butter', ranking: 50, item: new_item}, {name: 'Agave nectar', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Peanut butter')
Association.create!([{name: 'Ketchup', ranking: 50, item: new_item}, {name: 'Hot sauce', ranking: 50, item: new_item}, {name: 'Relish', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Ponzu')
Association.create!([{name: 'Harissa', ranking: 50, item: new_item}, {name: 'BBQ sauce', ranking: 50, item: new_item}, {name: 'Sriracha', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Salad dressing')
Association.create!([{name: 'BBQ sauce', ranking: 50, item: new_item}, {name: 'Gravy', ranking: 50, item: new_item}, {name: 'Harissa', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Salsa')
Association.create!([{name: 'Stir fry sauce', ranking: 50, item: new_item}, {name: 'Tomato sauce', ranking: 50, item: new_item}, {name: 'Brown rice syrup', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Soy sauce')
Association.create!([{name: 'Brown rice syrup', ranking: 50, item: new_item}, {name: 'Ketchup', ranking: 50, item: new_item}, {name: 'Relish', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sriracha')
Association.create!([{name: 'Salad dressing', ranking: 50, item: new_item}, {name: 'Peanut butter', ranking: 50, item: new_item}, {name: 'Worcestershire', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Stir fry sauce')
Association.create!([{name: 'Worcestershire', ranking: 50, item: new_item}, {name: 'Noodles', ranking: 50, item: new_item}, {name: 'Sriracha', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Tomato sauce')
Association.create!([{name: 'Peanut butter', ranking: 50, item: new_item}, {name: 'Soups', ranking: 50, item: new_item}, {name: 'BBQ sauce', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Worcestershire')
Association.create!([{name: 'Steak sauce', ranking: 50, item: new_item}, {name: 'Maple syrup', ranking: 50, item: new_item}, {name: 'Agave nectar', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Steak sauce')
Association.create!([{name: 'Tomato sauce', ranking: 50, item: new_item}, {name: 'Brown rice syrup', ranking: 50, item: new_item}, {name: 'Worcestershire', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Relish')
Association.create!([{name: 'Worcestershire', ranking: 50, item: new_item}, {name: 'Ketchup', ranking: 50, item: new_item}, {name: 'Mustard', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Club soda')
Association.create!([{name: 'Juices', ranking: 50, item: new_item}, {name: 'Water', ranking: 50, item: new_item}, {name: 'Kombucha', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Electrolyte water')
Association.create!([{name: 'Tonic', ranking: 50, item: new_item}, {name: 'Kombucha', ranking: 50, item: new_item}, {name: 'Juices', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Juices')
Association.create!([{name: 'Tonic', ranking: 50, item: new_item}, {name: 'Water', ranking: 50, item: new_item}, {name: 'Sports drink', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Kombucha')
Association.create!([{name: 'Tea', ranking: 50, item: new_item}, {name: 'Tonic', ranking: 50, item: new_item}, {name: 'Soda pop', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Soda pop')
Association.create!([{name: 'Club soda', ranking: 50, item: new_item}, {name: 'Kombucha', ranking: 50, item: new_item}, {name: 'Juices', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sports drink')
Association.create!([{name: 'Juices', ranking: 50, item: new_item}, {name: 'Water', ranking: 50, item: new_item}, {name: 'Tonic', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Tonic')
Association.create!([{name: 'Kombucha', ranking: 50, item: new_item}, {name: 'Club soda', ranking: 50, item: new_item}, {name: 'Soda pop', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Beer')
Association.create!([{name: 'Wine', ranking: 50, item: new_item}, {name: 'SakÃ©', ranking: 50, item: new_item}, {name: 'Gin', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Liquor')
Association.create!([{name: 'Wine', ranking: 50, item: new_item}, {name: 'Beer', ranking: 50, item: new_item}, {name: 'Mixers', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Mixers')
Association.create!([{name: 'SakÃ©', ranking: 50, item: new_item}, {name: 'Beer', ranking: 50, item: new_item}, {name: 'Liquor', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Champagne')
Association.create!([{name: 'Mixers', ranking: 50, item: new_item}, {name: 'Beer', ranking: 50, item: new_item}, {name: 'Wine', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Gin')
Association.create!([{name: 'Champagne', ranking: 50, item: new_item}, {name: 'Wine', ranking: 50, item: new_item}, {name: 'SakÃ©', ranking: 50, item: new_item}])
new_item = Item.create(name: 'SakÃ©')
Association.create!([{name: 'Liquor', ranking: 50, item: new_item}, {name: 'Beer', ranking: 50, item: new_item}, {name: 'Soy sauce', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Wine')
Association.create!([{name: 'Champagne', ranking: 50, item: new_item}, {name: 'Liquor', ranking: 50, item: new_item}, {name: 'Beer', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Almond butter')
Association.create!([{name: 'Cheddar cheese', ranking: 50, item: new_item}, {name: 'Whipped cream', ranking: 50, item: new_item}, {name: 'Milk', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Almond milk')
Association.create!([{name: 'Butter', ranking: 50, item: new_item}, {name: 'Almond butter', ranking: 50, item: new_item}, {name: 'Whipped cream', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Coconut milk')
Association.create!([{name: 'Soy sauce', ranking: 50, item: new_item}, {name: 'Flour', ranking: 50, item: new_item}, {name: 'Canned milk', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Bleu cheese')
Association.create!([{name: 'Feta cheese', ranking: 50, item: new_item}, {name: 'Whipped cream', ranking: 50, item: new_item}, {name: 'Salad Dressing', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Butter')
Association.create!([{name: 'Sour cream', ranking: 50, item: new_item}, {name: 'Ricotta', ranking: 50, item: new_item}, {name: 'Goat cheese', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cheddar cheese')
Association.create!([{name: 'Bleu cheese', ranking: 50, item: new_item}, {name: 'Margarine', ranking: 50, item: new_item}, {name: 'Sour cream', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cottage cheese')
Association.create!([{name: 'Bleu cheese', ranking: 50, item: new_item}, {name: 'Almond butter', ranking: 50, item: new_item}, {name: 'Rice milk', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cream cheese')
Association.create!([{name: 'Margarine', ranking: 50, item: new_item}, {name: 'Milk', ranking: 50, item: new_item}, {name: 'Cottage cheese', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cream')
Association.create!([{name: 'Provolone cheese', ranking: 50, item: new_item}, {name: 'Butter', ranking: 50, item: new_item}, {name: 'Yogurt', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Feta cheese')
Association.create!([{name: 'Ricotta', ranking: 50, item: new_item}, {name: 'Cream cheese', ranking: 50, item: new_item}, {name: 'Sour cream', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Margarine')
Association.create!([{name: 'Hummus', ranking: 50, item: new_item}, {name: 'Parmesan cheese', ranking: 50, item: new_item}, {name: 'Almond butter', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Milk')
Association.create!([{name: 'Sour cream', ranking: 50, item: new_item}, {name: 'Margarine', ranking: 50, item: new_item}, {name: 'Provolone cheese', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Mozzarella cheese')
Association.create!([{name: 'Swiss cheese', ranking: 50, item: new_item}, {name: 'Cream cheese', ranking: 50, item: new_item}, {name: 'Egg substitute', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Parmesan cheese')
Association.create!([{name: 'Rice milk', ranking: 50, item: new_item}, {name: 'Egg substitute', ranking: 50, item: new_item}, {name: 'Ricotta', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Provolone cheese')
Association.create!([{name: 'Cream cheese', ranking: 50, item: new_item}, {name: 'Ham slices', ranking: 50, item: new_item}, {name: 'Cottage cheese', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Rice milk')
Association.create!([{name: 'Yogurt', ranking: 50, item: new_item}, {name: 'Cereal', ranking: 50, item: new_item}, {name: 'Milk', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Ricotta')
Association.create!([{name: 'Rice milk', ranking: 50, item: new_item}, {name: 'Feta cheese', ranking: 50, item: new_item}, {name: 'Egg substitute', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Goat cheese')
Association.create!([{name: 'Hummus', ranking: 50, item: new_item}, {name: 'Mozzarella cheese', ranking: 50, item: new_item}, {name: 'Sausage', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sour cream')
Association.create!([{name: 'Yogurt', ranking: 50, item: new_item}, {name: 'Cheddar cheese', ranking: 50, item: new_item}, {name: 'Margarine', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Swiss cheese')
Association.create!([{name: 'Ricotta', ranking: 50, item: new_item}, {name: 'Hummus', ranking: 50, item: new_item}, {name: 'Whipped cream', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Whipped cream')
Association.create!([{name: 'Eggs', ranking: 50, item: new_item}, {name: 'Sour cream', ranking: 50, item: new_item}, {name: 'Ricotta', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Yogurt')
Association.create!([{name: 'Feta cheese', ranking: 50, item: new_item}, {name: 'Mozzarella cheese', ranking: 50, item: new_item}, {name: 'Sour cream', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Half & half')
Association.create!([{name: 'Eggs', ranking: 50, item: new_item}, {name: 'Cream cheese', ranking: 50, item: new_item}, {name: 'Cheddar cheese', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Eggs')
Association.create!([{name: 'Cottage cheese', ranking: 50, item: new_item}, {name: 'Whipped cream', ranking: 50, item: new_item}, {name: 'Bleu cheese', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Egg substitute')
Association.create!([{name: 'Swiss cheese', ranking: 50, item: new_item}, {name: 'Cream', ranking: 50, item: new_item}, {name: 'Provolone cheese', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Hummus')
Association.create!([{name: 'Butter', ranking: 50, item: new_item}, {name: 'Bleu cheese', ranking: 50, item: new_item}, {name: 'Ricotta', ranking: 50, item: new_item}])
new_item = Item.create(name: 'French Fries')
Association.create!([{name: 'Puff pastry', ranking: 50, item: new_item}, {name: 'Veggie breakfasts', ranking: 50, item: new_item}, {name: 'Prepared meals', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Tater tots')
Association.create!([{name: 'Popsicles', ranking: 50, item: new_item}, {name: 'Veggie burgers', ranking: 50, item: new_item}, {name: 'Prepared meals', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Ice cream')
Association.create!([{name: 'Tater tots', ranking: 50, item: new_item}, {name: 'Puff pastry', ranking: 50, item: new_item}, {name: 'Prepared meals', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Phyllo')
Association.create!([{name: 'Veggie breakfasts', ranking: 50, item: new_item}, {name: 'Frozen desserts', ranking: 50, item: new_item}, {name: 'Frozen bread dough', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Puff pastry')
Association.create!([{name: 'Veggie burgers', ranking: 50, item: new_item}, {name: 'Veggie breakfasts', ranking: 50, item: new_item}, {name: 'Frozen food', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Popsicles')
Association.create!([{name: 'French Fries', ranking: 50, item: new_item}, {name: 'Veggie burgers', ranking: 50, item: new_item}, {name: 'Frozen desserts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Prepared meals')
Association.create!([{name: 'Sorbet', ranking: 50, item: new_item}, {name: 'Phyllo', ranking: 50, item: new_item}, {name: 'Tater tots', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sorbet')
Association.create!([{name: 'Phyllo', ranking: 50, item: new_item}, {name: 'Veggie burritos', ranking: 50, item: new_item}, {name: 'Frozen desserts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Veggie breakfasts')
Association.create!([{name: 'Frozen food', ranking: 50, item: new_item}, {name: 'Veggie burgers', ranking: 50, item: new_item}, {name: 'Prepared meals', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Veggie burgers')
Association.create!([{name: 'Sorbet', ranking: 50, item: new_item}, {name: 'Veggie pizzas', ranking: 50, item: new_item}, {name: 'Veggie breakfasts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Veggie burritos')
Association.create!([{name: 'Frozen food', ranking: 50, item: new_item}, {name: 'Prepared meals', ranking: 50, item: new_item}, {name: 'Veggie pizzas', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Veggie pizzas')
Association.create!([{name: 'Frozen food', ranking: 50, item: new_item}, {name: 'Tater tots', ranking: 50, item: new_item}, {name: 'French Fries', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cereal')
Association.create!([{name: 'Tofu', ranking: 50, item: new_item}, {name: 'Waffle mix', ranking: 50, item: new_item}, {name: 'Pancake mix', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Chai')
Association.create!([{name: 'Mac & cheese', ranking: 50, item: new_item}, {name: 'Coffee', ranking: 50, item: new_item}, {name: 'Instant potatoes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Coffee')
Association.create!([{name: 'Waffle mix', ranking: 50, item: new_item}, {name: 'Chai', ranking: 50, item: new_item}, {name: 'Tea', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Coffee Filters')
Association.create!([{name: 'Chai', ranking: 50, item: new_item}, {name: 'Tofu', ranking: 50, item: new_item}, {name: 'Coffee', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Lemon juice')
Association.create!([{name: 'Waffle mix', ranking: 50, item: new_item}, {name: 'Instant potatoes', ranking: 50, item: new_item}, {name: 'Tea', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Lime juice')
Association.create!([{name: 'Pasta', ranking: 50, item: new_item}, {name: 'Lemon juice', ranking: 50, item: new_item}, {name: 'Apples', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Nutritional yeast')
Association.create!([{name: 'Waffle mix', ranking: 50, item: new_item}, {name: 'Tofu', ranking: 50, item: new_item}, {name: 'Coffee Filters', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pancake mix')
Association.create!([{name: 'Tempeh', ranking: 50, item: new_item}, {name: 'Coffee', ranking: 50, item: new_item}, {name: 'Tahini', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Waffle mix')
Association.create!([{name: 'Coffee', ranking: 50, item: new_item}, {name: 'Tahini', ranking: 50, item: new_item}, {name: 'Tea', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pasta')
Association.create!([{name: 'Mac & cheese', ranking: 50, item: new_item}, {name: 'Pancake mix', ranking: 50, item: new_item}, {name: 'Veggie dogs', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pickles')
Association.create!([{name: 'Nutritional yeast', ranking: 50, item: new_item}, {name: 'Olives', ranking: 50, item: new_item}, {name: 'Coffee', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Tahini')
Association.create!([{name: 'Veggie dogs', ranking: 50, item: new_item}, {name: 'Peanut butter', ranking: 50, item: new_item}, {name: 'Instant potatoes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Tea')
Association.create!([{name: 'Chai', ranking: 50, item: new_item}, {name: 'Lemon juice', ranking: 50, item: new_item}, {name: 'Coffee', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Tempeh')
Association.create!([{name: 'Tofu', ranking: 50, item: new_item}, {name: 'Chai', ranking: 50, item: new_item}, {name: 'Coffee Filters', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Tofu')
Association.create!([{name: 'Pasta', ranking: 50, item: new_item}, {name: 'Instant potatoes', ranking: 50, item: new_item}, {name: 'Tea', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Veggie dogs')
Association.create!([{name: 'Frozen food', ranking: 50, item: new_item}, {name: 'Coffee', ranking: 50, item: new_item}, {name: 'Pickles', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Mac & cheese')
Association.create!([{name: 'Veggie dogs', ranking: 50, item: new_item}, {name: 'Tea', ranking: 50, item: new_item}, {name: 'Bouillon cubes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Bouillon cubes')
Association.create!([{name: 'Lime juice', ranking: 50, item: new_item}, {name: 'Coffee', ranking: 50, item: new_item}, {name: 'Mac & cheese', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Instant potatoes')
Association.create!([{name: 'Tea', ranking: 50, item: new_item}, {name: 'Lime juice', ranking: 50, item: new_item}, {name: 'Coffee Filters', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Won ton skins')
Association.create!([{name: 'Tofu', ranking: 50, item: new_item}, {name: 'Eggroll wrappers', ranking: 50, item: new_item}, {name: 'Frozen food', ranking: 50, item: new_item}])
new_item = Item.create(name: 'English muffins')
Association.create!([{name: 'Pastries', ranking: 50, item: new_item}, {name: 'Bagels', ranking: 50, item: new_item}, {name: 'Pie', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Bagels')
Association.create!([{name: 'Fresh bread', ranking: 50, item: new_item}, {name: 'Tortillas', ranking: 50, item: new_item}, {name: 'Donuts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Croissants')
Association.create!([{name: 'English muffins', ranking: 50, item: new_item}, {name: 'Fresh bread', ranking: 50, item: new_item}, {name: 'Rolls', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Buns')
Association.create!([{name: 'Fresh bread', ranking: 50, item: new_item}, {name: 'Cake', ranking: 50, item: new_item}, {name: 'Pitas', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Rolls')
Association.create!([{name: 'English muffins', ranking: 50, item: new_item}, {name: 'Donuts', ranking: 50, item: new_item}, {name: 'Buns', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cake')
Association.create!([{name: 'English muffins', ranking: 50, item: new_item}, {name: 'Buns', ranking: 50, item: new_item}, {name: 'Pie', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Donuts')
Association.create!([{name: 'Fresh bread', ranking: 50, item: new_item}, {name: 'Sliced bread', ranking: 50, item: new_item}, {name: 'Cake', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pastries')
Association.create!([{name: 'Donuts', ranking: 50, item: new_item}, {name: 'Buns', ranking: 50, item: new_item}, {name: 'Sliced bread', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Fresh bread')
Association.create!([{name: 'Rolls', ranking: 50, item: new_item}, {name: 'Donuts', ranking: 50, item: new_item}, {name: 'Bagels', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sliced bread')
Association.create!([{name: 'Pastries', ranking: 50, item: new_item}, {name: 'Donuts', ranking: 50, item: new_item}, {name: 'Fresh bread', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pie')
Association.create!([{name: 'English muffins', ranking: 50, item: new_item}, {name: 'Croissants', ranking: 50, item: new_item}, {name: 'Cake', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pitas')
Association.create!([{name: 'Buns', ranking: 50, item: new_item}, {name: 'Croissants', ranking: 50, item: new_item}, {name: 'Bagels', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Tortillas')
Association.create!([{name: 'Bagels', ranking: 50, item: new_item}, {name: 'Pastries', ranking: 50, item: new_item}, {name: 'Cake', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cat food')
Association.create!([{name: 'Cat litter', ranking: 50, item: new_item}, {name: 'Flea treatment', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cat litter')
Association.create!([{name: 'Pet shampoo', ranking: 50, item: new_item}, {name: 'Flea treatment', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Dog food')
Association.create!([{name: 'Flea treatment', ranking: 50, item: new_item}, {name: 'Pet shampoo', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Flea treatment')
Association.create!([{name: 'Cat food', ranking: 50, item: new_item}, {name: 'Pet shampoo', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pet shampoo')
Association.create!([{name: 'Dog food', ranking: 50, item: new_item}, {name: 'Cat litter', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Baking powder')
Association.create!([{name: 'Cake decorations', ranking: 50, item: new_item}, {name: 'Chocolate cocoa', ranking: 50, item: new_item}, {name: 'Vegetable shortening', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Baking soda')
Association.create!([{name: 'Stevia', ranking: 50, item: new_item}, {name: 'Cake icing', ranking: 50, item: new_item}, {name: 'Cake decorations', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Corn starch')
Association.create!([{name: 'Flour', ranking: 50, item: new_item}, {name: 'Sugar', ranking: 50, item: new_item}, {name: 'Cake mix', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Bread crumbs')
Association.create!([{name: 'Stevia', ranking: 50, item: new_item}, {name: 'Yeast', ranking: 50, item: new_item}, {name: 'Sugar substitute', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Breadcrumbs')
Association.create!([{name: 'Vegetable shortening', ranking: 50, item: new_item}, {name: 'Cake icing', ranking: 50, item: new_item}, {name: 'Baking soda', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cake icing')
Association.create!([{name: 'Breadcrumbs', ranking: 50, item: new_item}, {name: 'Chocolate cocoa', ranking: 50, item: new_item}, {name: 'Sugar substitute', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cake decorations')
Association.create!([{name: 'Yeast', ranking: 50, item: new_item}, {name: 'Cake mix', ranking: 50, item: new_item}, {name: 'Baking powder', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cake mix')
Association.create!([{name: 'Vegetable shortening', ranking: 50, item: new_item}, {name: 'Chocolate chips', ranking: 50, item: new_item}, {name: 'Flour', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Brownie mix')
Association.create!([{name: 'Sugar substitute', ranking: 50, item: new_item}, {name: 'Baking powder', ranking: 50, item: new_item}, {name: 'Flour', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Chocolate chips')
Association.create!([{name: 'Baking powder', ranking: 50, item: new_item}, {name: 'Chocolate cocoa', ranking: 50, item: new_item}, {name: 'Vegetable shortening', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Chocolate cocoa')
Association.create!([{name: 'Baking soda', ranking: 50, item: new_item}, {name: 'Yeast', ranking: 50, item: new_item}, {name: 'Cake decorations', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Flour')
Association.create!([{name: 'Breadcrumbs', ranking: 50, item: new_item}, {name: 'Cake icing', ranking: 50, item: new_item}, {name: 'Yeast', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Stevia')
Association.create!([{name: 'Bread crumbs', ranking: 50, item: new_item}, {name: 'Baking powder', ranking: 50, item: new_item}, {name: 'Yeast', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sugar')
Association.create!([{name: 'Stevia', ranking: 50, item: new_item}, {name: 'Vegetable shortening', ranking: 50, item: new_item}, {name: 'Cake mix', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sugar substitute')
Association.create!([{name: 'Sugar', ranking: 50, item: new_item}, {name: 'Flour', ranking: 50, item: new_item}, {name: 'Brownie mix', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Vegetable shortening')
Association.create!([{name: 'Chocolate cocoa', ranking: 50, item: new_item}, {name: 'Cake mix', ranking: 50, item: new_item}, {name: 'Stevia', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Yeast')
Association.create!([{name: 'Cake decorations', ranking: 50, item: new_item}, {name: 'Chocolate chips', ranking: 50, item: new_item}, {name: 'Brownie mix', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Graham cracker crumbs')
Association.create!([{name: 'Crackers', ranking: 50, item: new_item}, {name: 'Flour', ranking: 50, item: new_item}, {name: 'Bread', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Apple cider vinegar')
Association.create!([{name: 'Vegetable oil', ranking: 50, item: new_item}, {name: 'Rice vinegar', ranking: 50, item: new_item}, {name: 'Olive oil', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Balsamic vinegar')
Association.create!([{name: 'Sesame oil', ranking: 50, item: new_item}, {name: 'White vinegar', ranking: 50, item: new_item}, {name: 'Olive oil', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Red wine vinegar')
Association.create!([{name: 'Sesame oil', ranking: 50, item: new_item}, {name: 'White vinegar', ranking: 50, item: new_item}, {name: 'Balsamic vinegar', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Rice vinegar')
Association.create!([{name: 'White vinegar', ranking: 50, item: new_item}, {name: 'Apple cider vinegar', ranking: 50, item: new_item}, {name: 'Olive oil', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sesame oil')
Association.create!([{name: 'Rice vinegar', ranking: 50, item: new_item}, {name: 'Apple cider vinegar', ranking: 50, item: new_item}, {name: 'Soy sauce', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Olive oil')
Association.create!([{name: 'Vegetable oil', ranking: 50, item: new_item}, {name: 'White vinegar', ranking: 50, item: new_item}, {name: 'Apple cider vinegar', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Vegetable oil')
Association.create!([{name: 'Balsamic vinegar', ranking: 50, item: new_item}, {name: 'Olive oil', ranking: 50, item: new_item}, {name: 'Apple cider vinegar', ranking: 50, item: new_item}])
new_item = Item.create(name: 'White vinegar')
Association.create!([{name: 'Olive oil', ranking: 50, item: new_item}, {name: 'Vegetable oil', ranking: 50, item: new_item}, {name: 'Balsamic vinegar', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Canola oil')
Association.create!([{name: 'Olive oil', ranking: 50, item: new_item}, {name: 'Vegetable oil', ranking: 50, item: new_item}, {name: 'Sesame oil', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Candy')
Association.create!([{name: 'Trail mix', ranking: 50, item: new_item}, {name: 'Prunes', ranking: 50, item: new_item}, {name: 'Cookies', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Gum')
Association.create!([{name: 'Granola bars', ranking: 50, item: new_item}, {name: 'Prunes', ranking: 50, item: new_item}, {name: 'Trail mix', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cookies')
Association.create!([{name: 'Popcorn', ranking: 50, item: new_item}, {name: 'Cereal bars', ranking: 50, item: new_item}, {name: 'Chip dip', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Ladyfingers')
Association.create!([{name: 'Cookies', ranking: 50, item: new_item}, {name: 'Cake', ranking: 50, item: new_item}, {name: 'Pasta', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Crackers')
Association.create!([{name: 'Cookies', ranking: 50, item: new_item}, {name: 'Cereal bars', ranking: 50, item: new_item}, {name: 'Granola bars', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Dried fruit')
Association.create!([{name: 'Cookies', ranking: 50, item: new_item}, {name: 'Pretzels', ranking: 50, item: new_item}, {name: 'Raisins', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Trail mix')
Association.create!([{name: 'Crackers', ranking: 50, item: new_item}, {name: 'Candy', ranking: 50, item: new_item}, {name: 'Cereal bars', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Granola bars')
Association.create!([{name: 'Cereal', ranking: 50, item: new_item}, {name: 'Popcorn', ranking: 50, item: new_item}, {name: 'Chip dip', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cereal bars')
Association.create!([{name: 'Trail mix', ranking: 50, item: new_item}, {name: 'Dried fruit', ranking: 50, item: new_item}, {name: 'Crackers', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Popcorn')
Association.create!([{name: 'Dried fruit', ranking: 50, item: new_item}, {name: 'Crackers', ranking: 50, item: new_item}, {name: 'Potato chips', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Potato chips')
Association.create!([{name: 'Granola bars', ranking: 50, item: new_item}, {name: 'Pretzels', ranking: 50, item: new_item}, {name: 'Popcorn', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Corn chips')
Association.create!([{name: 'Potato chips', ranking: 50, item: new_item}, {name: 'Cookies', ranking: 50, item: new_item}, {name: 'Chip dip', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Prunes')
Association.create!([{name: 'Flour', ranking: 50, item: new_item}, {name: 'Dried fruit', ranking: 50, item: new_item}, {name: 'Raisins', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Raisins')
Association.create!([{name: 'Cookies', ranking: 50, item: new_item}, {name: 'Cereal bars', ranking: 50, item: new_item}, {name: 'Peanuts', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pretzels')
Association.create!([{name: 'Potato chips', ranking: 50, item: new_item}, {name: 'Cookies', ranking: 50, item: new_item}, {name: 'Raisins', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Chip dip')
Association.create!([{name: 'Cereal bars', ranking: 50, item: new_item}, {name: 'Pretzels', ranking: 50, item: new_item}, {name: 'Potato chips', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Energy bars')
Association.create!([{name: 'Granola bars', ranking: 50, item: new_item}, {name: 'Toothbrushes', ranking: 50, item: new_item}, {name: 'Vitamins', ranking: 50, item: new_item}])
new_item = Item.create(name: 'CDRs')
Association.create!([{name: 'Glue', ranking: 50, item: new_item}, {name: 'DVDRs', ranking: 50, item: new_item}])
new_item = Item.create(name: 'DVDRs')
Association.create!([{name: 'Glue', ranking: 50, item: new_item}, {name: 'Envelopes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Notepads')
Association.create!([{name: 'Pens', ranking: 50, item: new_item}, {name: 'Tape', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Envelopes')
Association.create!([{name: 'Tape', ranking: 50, item: new_item}, {name: 'Printer paper', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Glue')
Association.create!([{name: 'Tape', ranking: 50, item: new_item}, {name: 'Printer paper', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Tape')
Association.create!([{name: 'Glue', ranking: 50, item: new_item}, {name: 'Notepads', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Printer paper')
Association.create!([{name: 'Pens', ranking: 50, item: new_item}, {name: 'Notepads', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pens')
Association.create!([{name: 'Glue', ranking: 50, item: new_item}, {name: 'Notepads', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Air freshener')
Association.create!([{name: 'Dishwasher soap', ranking: 50, item: new_item}, {name: 'Candles', ranking: 50, item: new_item}, {name: 'Bathroom cleaner', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Bathroom cleaner')
Association.create!([{name: 'Laundry detergent', ranking: 50, item: new_item}, {name: 'Dishwasher soap', ranking: 50, item: new_item}, {name: 'Garbage bags', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Bleach')
Association.create!([{name: 'Air freshener', ranking: 50, item: new_item}, {name: 'Laundry detergent', ranking: 50, item: new_item}, {name: 'Bathroom cleaner', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Laundry detergent')
Association.create!([{name: 'Air freshener', ranking: 50, item: new_item}, {name: 'Bleach', ranking: 50, item: new_item}, {name: 'Dish detergent', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Dish detergent')
Association.create!([{name: 'Bathroom cleaner', ranking: 50, item: new_item}, {name: 'Bleach', ranking: 50, item: new_item}, {name: 'Laundry detergent', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Dishwasher soap')
Association.create!([{name: 'Bathroom cleaner', ranking: 50, item: new_item}, {name: 'Bleach', ranking: 50, item: new_item}, {name: 'Air freshener', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Garbage bags')
Association.create!([{name: 'Dishwasher soap', ranking: 50, item: new_item}, {name: 'Air freshener', ranking: 50, item: new_item}, {name: 'Bathroom cleaner', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Glass cleaner')
Association.create!([{name: 'Dishwasher soap', ranking: 50, item: new_item}, {name: 'Bleach', ranking: 50, item: new_item}, {name: 'Silverware', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Mop')
Association.create!([{name: 'Dishwasher soap', ranking: 50, item: new_item}, {name: 'Bathroom cleaner', ranking: 50, item: new_item}, {name: 'Brooms', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Vacuum bags')
Association.create!([{name: 'Laundry detergent', ranking: 50, item: new_item}, {name: 'Bleach', ranking: 50, item: new_item}, {name: 'Bathroom cleaner', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sponges')
Association.create!([{name: 'Bleach', ranking: 50, item: new_item}, {name: 'Bathroom cleaner', ranking: 50, item: new_item}, {name: 'Laundry detergent', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Scrubbers')
Association.create!([{name: 'Bleach', ranking: 50, item: new_item}, {name: 'Bathroom cleaner', ranking: 50, item: new_item}, {name: 'Sponges', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Aluminum foil')
Association.create!([{name: 'Freezer bags', ranking: 50, item: new_item}, {name: 'Plastic wrap', ranking: 50, item: new_item}, {name: 'Paper towels', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Napkins')
Association.create!([{name: 'Paper towels', ranking: 50, item: new_item}, {name: 'Freezer bags', ranking: 50, item: new_item}, {name: 'Non-stick spray', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Non-stick spray')
Association.create!([{name: 'Paper plates', ranking: 50, item: new_item}, {name: 'Canola oil', ranking: 50, item: new_item}, {name: 'Paper towels', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Paper towels')
Association.create!([{name: 'Freezer bags', ranking: 50, item: new_item}, {name: 'Paper plates', ranking: 50, item: new_item}, {name: 'Plastic wrap', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Plastic wrap')
Association.create!([{name: 'Non-stick spray', ranking: 50, item: new_item}, {name: 'Wax paper', ranking: 50, item: new_item}, {name: 'Paper plates', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sandwich bags')
Association.create!([{name: 'Paper plates', ranking: 50, item: new_item}, {name: 'Napkins', ranking: 50, item: new_item}, {name: 'Freezer bags', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Freezer bags')
Association.create!([{name: 'Aluminum foil', ranking: 50, item: new_item}, {name: 'Plastic wrap', ranking: 50, item: new_item}, {name: 'Paper plates', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Wax paper')
Association.create!([{name: 'Paper plates', ranking: 50, item: new_item}, {name: 'Plastic wrap', ranking: 50, item: new_item}, {name: 'Sandwich bags', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Allergy meds')
Association.create!([{name: 'Antidiarrheal', ranking: 50, item: new_item}, {name: 'Antacid', ranking: 50, item: new_item}, {name: 'Toothbrushes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Antibiotic meds')
Association.create!([{name: 'Antidiarrheal', ranking: 50, item: new_item}, {name: 'Toothbrushes', ranking: 50, item: new_item}, {name: 'Cold, Flu, Sinus', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Antidiarrheal')
Association.create!([{name: 'Allergy meds', ranking: 50, item: new_item}, {name: 'Toothbrushes', ranking: 50, item: new_item}, {name: 'Soap', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Aspirin')
Association.create!([{name: 'Pain reliever', ranking: 50, item: new_item}, {name: 'Band-aids', ranking: 50, item: new_item}, {name: 'Antacid', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Antacid')
Association.create!([{name: 'Aspirin', ranking: 50, item: new_item}, {name: 'Toothbrushes', ranking: 50, item: new_item}, {name: 'Cold, Flu, Sinus', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Band-aids')
Association.create!([{name: 'Toothbrushes', ranking: 50, item: new_item}, {name: 'Antidiarrheal', ranking: 50, item: new_item}, {name: 'Antibiotic meds', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cold, Flu, Sinus')
Association.create!([{name: 'Pain reliever', ranking: 50, item: new_item}, {name: 'Antibiotic meds', ranking: 50, item: new_item}, {name: 'Toothbrushes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pain reliever')
Association.create!([{name: 'Cold, Flu, Sinus', ranking: 50, item: new_item}, {name: 'Band-aids', ranking: 50, item: new_item}, {name: 'Antibiotic meds', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Antiperspirant')
Association.create!([{name: 'Razors', ranking: 50, item: new_item}, {name: 'Facial cleanser', ranking: 50, item: new_item}, {name: 'Shaving cream', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Soap')
Association.create!([{name: 'Facial cleanser', ranking: 50, item: new_item}, {name: 'Moisturizing lotion', ranking: 50, item: new_item}, {name: 'Cosmetics', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cosmetics')
Association.create!([{name: 'Shaving cream', ranking: 50, item: new_item}, {name: 'Antiperspirant', ranking: 50, item: new_item}, {name: 'Facial cleanser', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Cotton swabs')
Association.create!([{name: 'Soap', ranking: 50, item: new_item}, {name: 'Hair gel', ranking: 50, item: new_item}, {name: 'Razors', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Facial cleanser')
Association.create!([{name: 'Soap', ranking: 50, item: new_item}, {name: 'Shampoo', ranking: 50, item: new_item}, {name: 'Cosmetics', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Facial tissue')
Association.create!([{name: 'Hair gel', ranking: 50, item: new_item}, {name: 'Soap', ranking: 50, item: new_item}, {name: 'Toilet paper', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Floss')
Association.create!([{name: 'Hair spray', ranking: 50, item: new_item}, {name: 'Mouthwash', ranking: 50, item: new_item}, {name: 'Facial tissue', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Hair spray')
Association.create!([{name: 'Cotton swabs', ranking: 50, item: new_item}, {name: 'Shampoo', ranking: 50, item: new_item}, {name: 'Razors', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Hair gel')
Association.create!([{name: 'Toothpaste', ranking: 50, item: new_item}, {name: 'Shampoo', ranking: 50, item: new_item}, {name: 'Soap', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Lip balm')
Association.create!([{name: 'Vitamins', ranking: 50, item: new_item}, {name: 'Antiperspirant', ranking: 50, item: new_item}, {name: 'Cotton swabs', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Moisturizing lotion')
Association.create!([{name: 'Toilet paper', ranking: 50, item: new_item}, {name: 'Cosmetics', ranking: 50, item: new_item}, {name: 'Hair gel', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Mouthwash')
Association.create!([{name: 'Hair gel', ranking: 50, item: new_item}, {name: 'Lip balm', ranking: 50, item: new_item}, {name: 'Moisturizing lotion', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Shaving cream')
Association.create!([{name: 'Facial tissue', ranking: 50, item: new_item}, {name: 'Razors', ranking: 50, item: new_item}, {name: 'Shampoo', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Razors')
Association.create!([{name: 'Antiperspirant', ranking: 50, item: new_item}, {name: 'Vitamins', ranking: 50, item: new_item}, {name: 'Shampoo', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Conditioner')
Association.create!([{name: 'Sunblock', ranking: 50, item: new_item}, {name: 'Soap', ranking: 50, item: new_item}, {name: 'Deodorant', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Shampoo')
Association.create!([{name: 'Mouthwash', ranking: 50, item: new_item}, {name: 'Cotton swabs', ranking: 50, item: new_item}, {name: 'Floss', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sunblock')
Association.create!([{name: 'Antiperspirant', ranking: 50, item: new_item}, {name: 'Toilet paper', ranking: 50, item: new_item}, {name: 'Cotton swabs', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Toilet paper')
Association.create!([{name: 'Cotton swabs', ranking: 50, item: new_item}, {name: 'Facial tissue', ranking: 50, item: new_item}, {name: 'Toothpaste', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Toothpaste')
Association.create!([{name: 'Hair gel', ranking: 50, item: new_item}, {name: 'Toothbrushes', ranking: 50, item: new_item}, {name: 'Cotton swabs', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Vitamins')
Association.create!([{name: 'Mouthwash', ranking: 50, item: new_item}, {name: 'Shaving cream', ranking: 50, item: new_item}, {name: 'Hair spray', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Deodorant')
Association.create!([{name: 'Lip balm', ranking: 50, item: new_item}, {name: 'Shaving cream', ranking: 50, item: new_item}, {name: 'Toothbrushes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Baby food')
Association.create!([{name: 'Wipes', ranking: 50, item: new_item}, {name: 'Diapers', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Diapers')
Association.create!([{name: 'Wipes', ranking: 50, item: new_item}, {name: 'Formula', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Formula')
Association.create!([{name: 'Diapers', ranking: 50, item: new_item}, {name: 'Baby food', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Baby wash')
Association.create!([{name: 'Formula', ranking: 50, item: new_item}, {name: 'Wipes', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Wipes')
Association.create!([{name: 'Formula', ranking: 50, item: new_item}, {name: 'Diapers', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Bacon')
Association.create!([{name: 'Chicken', ranking: 50, item: new_item}, {name: 'Sausage', ranking: 50, item: new_item}, {name: 'Eggs', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Sausage')
Association.create!([{name: 'Turkey', ranking: 50, item: new_item}, {name: 'Lunchmeat', ranking: 50, item: new_item}, {name: 'Chicken', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Pork')
Association.create!([{name: 'Ham', ranking: 50, item: new_item}, {name: 'Ground beef', ranking: 50, item: new_item}, {name: 'Bacon', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Chicken')
Association.create!([{name: 'Pork', ranking: 50, item: new_item}, {name: 'Turkey', ranking: 50, item: new_item}, {name: 'Beef', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Ground beef')
Association.create!([{name: 'Bacon', ranking: 50, item: new_item}, {name: 'Sausage', ranking: 50, item: new_item}, {name: 'Pork', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Ham')
Association.create!([{name: 'Chicken', ranking: 50, item: new_item}, {name: 'Cheese', ranking: 50, item: new_item}, {name: 'Turkey', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Hot dogs')
Association.create!([{name: 'Turkey', ranking: 50, item: new_item}, {name: 'Ham', ranking: 50, item: new_item}, {name: 'Chicken', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Lunchmeat')
Association.create!([{name: 'Pork', ranking: 50, item: new_item}, {name: 'Cheese', ranking: 50, item: new_item}, {name: 'Bacon', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Turkey')
Association.create!([{name: 'Sausage', ranking: 50, item: new_item}, {name: 'Bacon', ranking: 50, item: new_item}, {name: 'Cheese', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Catfish')
Association.create!([{name: 'Crab', ranking: 50, item: new_item}, {name: 'Shrimp', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Crab')
Association.create!([{name: 'Oysters', ranking: 50, item: new_item}, {name: 'Salmon', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Lobster')
Association.create!([{name: 'Shrimp', ranking: 50, item: new_item}, {name: 'Tuna', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Mussels')
Association.create!([{name: 'Lobster', ranking: 50, item: new_item}, {name: 'Catfish', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Oysters')
Association.create!([{name: 'Shrimp', ranking: 50, item: new_item}, {name: 'Tuna', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Salmon')
Association.create!([{name: 'Crab', ranking: 50, item: new_item}, {name: 'Lobster', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Shrimp')
Association.create!([{name: 'Catfish', ranking: 50, item: new_item}, {name: 'Crab', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Tilapia')
Association.create!([{name: 'Salmon', ranking: 50, item: new_item}, {name: 'Crab', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Tuna')
Association.create!([{name: 'Salmon', ranking: 50, item: new_item}, {name: 'Catfish', ranking: 50, item: new_item}])
new_item = Item.create(name: 'Quinoa')
Association.create!([{name: 'Rice', ranking: 100, item: new_item}, {name: 'Grains', ranking: 90, item: new_item}, {name: 'Beans', ranking: 80, item: new_item}, {name: 'Flour', ranking: 75, item: new_item}, {name: 'Organize items', ranking: 60, item: new_item}, {name: 'Barley', ranking: 55, item: new_item}])